#!/bin/bash
# Quick launch guide for trace62 and trace63

echo "=========================================="
echo "Trace62 & Trace63 Quick Launch Guide"
echo "=========================================="
echo ""
echo "📋 Experiments Overview:"
echo ""
echo "  Trace62: Multi-gate curriculum (gates: -1.5, -0.5, 0.6)"
echo "    - Progressive bonuses: 0.5, 1.0, 2.0"
echo "    - GPU: 2"
echo "    - Goal: Stepwise reward improvement"
echo ""
echo "  Trace63: Smooth gate reward (gate: -1.0, sigmoid)"
echo "    - Smooth transition with temperature 0.5"
echo "    - GPU: 3"
echo "    - Goal: Continuous reward gradient"
echo ""
echo "=========================================="
echo "🚀 Launch Commands:"
echo "=========================================="
echo ""
echo "Launch Trace62:"
echo "  ./scripts/launch_trace62.sh"
echo ""
echo "Launch Trace63:"
echo "  ./scripts/launch_trace63.sh"
echo ""
echo "Launch Both (parallel):"
echo "  ./scripts/launch_trace62.sh && ./scripts/launch_trace63.sh"
echo ""
echo "=========================================="
echo "📊 Monitor Progress:"
echo "=========================================="
echo ""
echo "Training logs:"
echo "  tail -f logs/trace62_multi_gates_train.log"
echo "  tail -f logs/trace63_smooth_gate_train.log"
echo ""
echo "tFold completion:"
echo "  tail -f logs/trace62_multi_gates_tfold_completion.log"
echo "  tail -f logs/trace63_smooth_gate_tfold_completion.log"
echo ""
echo "Checkpoints:"
echo "  watch -n 10 'ls -lh output/trace62_multi_gates/checkpoints/'"
echo "  watch -n 10 'ls -lh output/trace63_smooth_gate/checkpoints/'"
echo ""
echo "Online pool:"
echo "  tail -f output/trace62_multi_gates/online_tcr_pool_events.jsonl"
echo "  tail -f output/trace63_smooth_gate/online_tcr_pool_events.jsonl"
echo ""
echo "=========================================="
echo "🎯 Success Criteria:"
echo "=========================================="
echo ""
echo "Target: Mean reward > -1.0"
echo ""
echo "Trace62:"
echo "  ✓ 30%+ episodes pass gate1 (-1.5)"
echo "  ✓ 15%+ episodes pass gate2 (-0.5)"
echo "  ✓ Mean reward > -1.0"
echo ""
echo "Trace63:"
echo "  ✓ Smooth reward curve"
echo "  ✓ No training instability"
echo "  ✓ Mean reward > -1.0"
echo ""
echo "=========================================="
echo "📈 Analysis Commands:"
echo "=========================================="
echo ""
echo "After 20K steps, analyze rewards:"
echo ""
echo "python3 << 'EOF'"
echo "import json"
echo "import numpy as np"
echo ""
echo "# Trace62"
echo "affs62 = []"
echo "with open('output/trace62_multi_gates/online_tcr_pool_events.jsonl') as f:"
echo "    for line in f:"
echo "        affs62.append(json.loads(line)['affinity'])"
echo ""
echo "print('Trace62 (Multi-gate):')"
echo "print(f'  Mean affinity: {np.mean(affs62):.3f}')"
echo "print(f'  Pass gate1 (-1.5): {sum(1 for a in affs62 if a > -1.5)/len(affs62)*100:.1f}%')"
echo "print(f'  Pass gate2 (-0.5): {sum(1 for a in affs62 if a > -0.5)/len(affs62)*100:.1f}%')"
echo "print(f'  Pass gate3 (0.6): {sum(1 for a in affs62 if a > 0.6)/len(affs62)*100:.1f}%')"
echo ""
echo "# Trace63"
echo "affs63 = []"
echo "with open('output/trace63_smooth_gate/online_tcr_pool_events.jsonl') as f:"
echo "    for line in f:"
echo "        affs63.append(json.loads(line)['affinity'])"
echo ""
echo "print('\\nTrace63 (Smooth gate):')"
echo "print(f'  Mean affinity: {np.mean(affs63):.3f}')"
echo "print(f'  Above gate (-1.0): {sum(1 for a in affs63 if a > -1.0)/len(affs63)*100:.1f}%')"
echo "EOF"
echo ""
echo "=========================================="
echo "⚠️  Important Notes:"
echo "=========================================="
echo ""
echo "1. Both experiments resume from trace61 600K checkpoint"
echo "2. GPU 2 and GPU 3 must be available"
echo "3. Estimated time: 2-3 hours for 20K steps"
echo "4. Check GPU usage: nvidia-smi"
echo "5. Stop training: kill <PID> (shown after launch)"
echo ""
echo "=========================================="
echo "📖 Full Documentation:"
echo "=========================================="
echo ""
echo "  cat TRACE62_63_DESIGN.md"
echo ""
echo "=========================================="
